

service: nest-track-service

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  profile: default
  memorySize: 256 
  # stage: dev

functions:
  main:
    handler: dist/src/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: "{proxy+}"

custom:
  serverless-offline:
    noPrependStageInUrl: true